ALTER TABLE posts ADD COLUMN owner bigint REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE topics ADD COLUMN owner bigint REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE posts ALTER COLUMN owner DROP NOT NULL;
ALTER TABLE topics ALTER COLUMN owner DROP NOT NULL;
